version: '2'
services:
  api:
    build: ./api
    network_mode: "bridge"
    ports:
    - "20000:20000"
    depends_on:
    - db
  db:
    build: ./db
    network_mode: "bridge"
    ports:
    - "24017:24017"
