version: '2'
services:
  api:
    build: ./api 
    network_mode: "bridge"
    ports:
    - "20000:20000"
    links:
    - db
    depends_on:
    - db
  db:
    command: ["mongod", "--auth", "--bind_ip", "0.0.0.0", "--port", "27017"] 
    build: ./db
    network_mode: "bridge"
    ports:
    - "27017:27017"
