[profile.dev]
debug = true

[package]
name = "api"
version = "0.0.1"
authors = ["Vignesh Sankaran <developer@ferndrop.com>"]
build = "build.rs"

[lib]
name = "prebuild"
path = "prebuild.rs"

[build-dependencies]
serde_codegen = "0.8.10"
runas = "= 0.1.1"

[features]
default = ["dev-local-nightly"]
dev-local-nightly = []
dev-local-stable = []

[dependencies]
iron = { version = "= 0.4.0", features = ["ssl"] }
router = "= 0.4.0"
uuid = { version = "= 0.3.1", features = ["v4"] }
serde = "0.8.10"
serde_json = "= 0.8.2"