[profile.dev]
debug = true

[package]
name = "api"
version = "0.0.1"
authors = ["Vignesh Sankaran <developer@ferndrop.com>"]
build = "build.rs"

[lib]
name = "prebuild"
path = "prebuild.rs"

[build-dependencies]
diesel_codegen_syntex = { version = "0.9.0", features = ["postgres"] }
serde_codegen = "0.8.21"
runas = "0.1.1"

[dependencies]
iron = { version = "0.4.0", features = ["ssl"] }
router = "0.4.0"
uuid = { version = "0.3.1", features = ["v4"] }
serde = "0.8.21"
serde_json = "0.8.4"
diesel = "0.9.1"
dotenv = "0.8.0"