[package]
name = "api"
version = "0.0.1"
authors = ["Vignesh Sankaran <vignesh.sankaran@ferndrop.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.8.18"

[dependencies]
iron = { version = "= 0.4.0", features = ["ssl"] }
router = "= 0.4.0"
serde = "= 0.8.18"
serde_json = "= 0.8.3"
uuid = { version = "= 0.3.1", features = ["v4"] }