[profile.dev]
debug = true

[package]
name = "api"
version = "0.0.1"
authors = ["Vignesh Sankaran <developer@ferndrop.com>"]

[lib]
name = "prebuild"
path = "prebuild.rs"

[dependencies]
iron = "= 0.4.0"
router = "= 0.4.0"
uuid = { version = "= 0.3.1", features = ["v4"] }
